### ISSUE TITLE
ERT Code problems

### ISSUE THREAD

**Issue by cszzy** [tsinghua-ideal/ExtendibleRadixTree#1]
Hello, I'am interested in your paper, thanks for your great job.
When I begin to learn your code, I find the ERT code seems not has concurrency control and recovery logic.
May you fix this issue? 
Thanks a lot!

**Comment by skyelves** [comment]
Thanks for the question! As we mentioned in the paper, concurrency control and recovery logic is not the main focus of ERT so we don't want to distract the reader attention to this part. As in experiments, we do implement a concurrent ERT with classic read-write lock. For recovery, we traverse the whole tree to recover infected nodes during the system crash. If you would like to dive into the implementation details of our experiments, please refer to https://github.com/skyelves/nvmkv.

**Comment by cszzy** [comment]
Thanks!
